import { z } from 'zod'
import { mapNetworkError, throwForResponse } from '../llm/http'
import { imageGenModel } from './types'
import type {
  ImageGenModel,
  ImageGenProvider,
  ImageGenRequest,
  ImageGenResult,
  ReferenceLimits,
  StockCallOptions,
} from './types'

/**
 * fal.ai running FLUX — the alternative `still` slot generator. Which FLUX
 * runs is `modelRouting.stills` (decision 208); the ids are fal's model
 * paths, appended to `fal.run`, and all three share the request/response
 * shape this adapter speaks.
 *
 * The synchronous endpoint (`fal.run`) rather than the queue: a two-image
 * generation returns in seconds, comfortably inside one Inngest step, and the
 * queue's submit/poll dance is machinery this call does not need.
 *
 * FLUX has no negative-prompt input — it is guidance-distilled, so the
 * SD-style parameter simply does not exist on the API. The brief's negative
 * prompt is folded into the prompt as an "Avoid:" clause instead, which FLUX
 * does honour; folded rather than dropped, because the brief writer said
 * something and silently ignoring it is the thing spec principle 6 forbids.
 */

/**
 * Prices are USD per image, rounded UP so the estimate errs against the
 * budget. dev and Krea: $0.025/megapixel and the 16:9 size is ~1.03 MP.
 * schnell: $0.003/megapixel. pro 1.1: a flat $0.04 per image. FLUX.2 dev:
 * $0.012/megapixel.
 *
 * The list is a promise, not a preference: every id here has been checked
 * against fal's OpenAPI schema and carries a price the budget maths can
 * trust. fal hosts hundreds of models behind other schemas; an id added
 * without that check would fail mid-run with money already spent. Known
 * incompatible: FLUX.2 pro and FLUX1.1 ultra take no `num_images` (one image
 * per request), which breaks the N-variants call shape. Checked and absent:
 * every Imagen 4 id (`fal-ai/imagen4/preview` and variants) 404s on fal's
 * schema endpoint — withdrawn, so not offered.
 *
 * Two wire dialects behind one contract (`prompt` + `num_images` in,
 * `images[]` out): the FLUX family takes `image_size: 'landscape_16_9'` and
 * no negative-prompt field; `fal-ai/imagen3` takes `aspect_ratio: '16:9'`
 * and a REAL `negative_prompt` field, so for it the brief's negative prompt
 * travels as itself rather than folded into an "Avoid:" clause.
 */
const MODELS = [
  { id: 'fal-ai/flux/dev', label: 'FLUX.1 dev', pricePerImage: 0.03 },
  { id: 'fal-ai/flux/schnell', label: 'FLUX.1 schnell', pricePerImage: 0.01 },
  { id: 'fal-ai/flux-pro/v1.1', label: 'FLUX1.1 pro', pricePerImage: 0.04 },
  { id: 'fal-ai/flux-2', label: 'FLUX.2 dev', pricePerImage: 0.02 },
  { id: 'fal-ai/flux/krea', label: 'FLUX.1 Krea dev', pricePerImage: 0.03 },
  { id: 'fal-ai/imagen3', label: 'Imagen 3', pricePerImage: 0.05 },
] as const

const isImagen = (model: string) => model === 'fal-ai/imagen3'

/**
 * Identity-conditioned generation (decision 253, amended 2026-09-16).
 *
 * No text-to-image endpoint takes a photograph, so a still that depicts cast
 * members has to be generated by a different endpoint from the routed one.
 * The rule is to stay inside the family the producer chose, because a still
 * that silently jumps model family stops matching the ones around it.
 *
 * FLUX.2 has its own reference endpoint, `fal-ai/flux-2/edit`, which takes an
 * `image_urls` array for one reference or several and speaks the FLUX dialect
 * (`image_size`). Everything else routes to FLUX.1 Kontext, which speaks its
 * own (`aspect_ratio`, and a separate id for one image versus several).
 *
 * Verified against fal's OpenAPI schema on 2026-09-16 rather than by probing
 * the run endpoint: a GET there answers 405 for any path, because fal checks
 * the key before the method, so it proves the key is live and nothing about
 * the model. The schema is the only thing that proves a path exists and takes
 * the fields sent. Checked and absent: `fal-ai/flux-2` and `fal-ai/flux-2-dev`
 * have NO image input of any kind, which is why FLUX.2 dev could never carry
 * a reference itself.
 *
 * Prices are per image, rounded up: Kontext pro $0.04, Kontext max multi
 * $0.08, FLUX.2 edit the FLUX.2 megapixel rate with headroom for the
 * reference inputs it also bills.
 */
const KONTEXT_SINGLE = {
  id: 'fal-ai/flux-pro/kontext',
  label: 'FLUX.1 Kontext pro',
  pricePerImage: 0.04,
} as const
const KONTEXT_MULTI = {
  id: 'fal-ai/flux-pro/kontext/max/multi',
  label: 'FLUX.1 Kontext max, multi',
  pricePerImage: 0.08,
} as const
const FLUX2_EDIT = { id: 'fal-ai/flux-2/edit', label: 'FLUX.2 edit', pricePerImage: 0.03 } as const

export const FAL_REFERENCE_MODELS = {
  single: KONTEXT_SINGLE,
  multi: KONTEXT_MULTI,
  flux2: FLUX2_EDIT,
} as const

/** The FLUX.2 text-to-image ids, whose references belong on `flux-2/edit`. */
const FLUX2_MODELS = new Set(['fal-ai/flux-2', 'fal-ai/flux-2-dev'])

/** Which wire dialect an endpoint speaks for its image inputs. */
type ReferenceDialect = 'flux2-edit' | 'kontext'

type ReferenceRoute = ImageGenModel & { dialect: ReferenceDialect }

/**
 * The endpoint that carries this model's references, or null when there are
 * none to carry. Imagen has no reference endpoint of its own on fal, so it
 * borrows Kontext: a likeness the producer asked for beats staying in family.
 */
function resolveReferenceRoute(modelId: string, refs: number): ReferenceRoute | null {
  if (refs === 0) return null
  if (FLUX2_MODELS.has(modelId)) return { ...FLUX2_EDIT, dialect: 'flux2-edit' }
  return refs === 1
    ? { ...KONTEXT_SINGLE, dialect: 'kontext' }
    : { ...KONTEXT_MULTI, dialect: 'kontext' }
}

/** Imagen's 16:9 renders 1408×768 — same class as FLUX's, scaled at compile. */
const IMAGEN_WIDTH = 1408
const IMAGEN_HEIGHT = 768

const endpoint = (model: string) => `https://fal.run/${model}`

const ResponseSchema = z.object({
  images: z.array(
    z.object({
      url: z.string(),
      width: z.number().nullish(),
      height: z.number().nullish(),
    }),
  ),
})

/** The render is 1920×1080; fal's preset generates 1344×768, scaled at compile. */
const IMAGE_SIZE = 'landscape_16_9'

export const falImageGen: ImageGenProvider = {
  id: 'fal',
  label: 'FLUX via fal.ai',
  models: MODELS,

  async generate(request: ImageGenRequest, options: StockCallOptions): Promise<ImageGenResult> {
    const apiKey = options.apiKey
    if (!apiKey) throw new Error('fal requires an API key')

    // Resolved (and refused, on an unknown id) before any call is made.
    const model = imageGenModel(falImageGen, request.model)
    const imagen = isImagen(model.id)

    // FLUX has no negative-prompt field, so the brief's negative prompt is
    // folded in as an "Avoid:" clause. Imagen has the real field.
    const prompt =
      request.negativePrompt && !imagen
        ? `${request.prompt}. Avoid: ${request.negativePrompt}.`
        : request.prompt

    const referenceUrls = request.referenceUrls ?? []
    const conditioned = resolveReferenceRoute(model.id, referenceUrls.length)

    const body = conditioned
      ? conditioned.dialect === 'flux2-edit'
        ? {
            prompt,
            // One field for one reference or several, unlike Kontext.
            image_urls: referenceUrls,
            image_size: IMAGE_SIZE,
            num_images: request.count,
            enable_safety_checker: true,
          }
        : {
            prompt,
            ...(referenceUrls.length === 1
              ? { image_url: referenceUrls[0] }
              : { image_urls: referenceUrls }),
            aspect_ratio: '16:9',
            num_images: request.count,
            safety_tolerance: '2',
          }
      : imagen
        ? {
            prompt,
            ...(request.negativePrompt ? { negative_prompt: request.negativePrompt } : {}),
            aspect_ratio: '16:9',
            num_images: request.count,
          }
        : {
            prompt,
            image_size: IMAGE_SIZE,
            num_images: request.count,
            enable_safety_checker: true,
          }

    const fetchImpl = options.fetchImpl ?? fetch
    let response: Response
    try {
      response = await fetchImpl(endpoint(conditioned ? conditioned.id : model.id), {
        method: 'POST',
        headers: {
          Authorization: `Key ${apiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(body),
        ...(options.signal ? { signal: options.signal } : {}),
      })
    } catch (cause) {
      throw mapNetworkError('fal', cause)
    }
    if (!response.ok) await throwForResponse('fal', response)

    const parsed = ResponseSchema.parse(await response.json())

    return {
      images: parsed.images.map((image) => ({
        url: image.url,
        width: image.width ?? (imagen ? IMAGEN_WIDTH : 1344),
        height: image.height ?? (imagen ? IMAGEN_HEIGHT : 768),
      })),
      estimatedCostUsd:
        (conditioned ? conditioned.pricePerImage : model.pricePerImage) * parsed.images.length,
    }
  },

  /**
   * fal caps nothing; its reference endpoint simply costs more per image
   * above one (see `resolveReferenceRoute`). These are the app's own limits,
   * chosen for what a still can usefully carry rather than what the endpoint
   * will accept.
   */
  referenceLimits(): ReferenceLimits {
    return { characters: 3, objects: 2 }
  },

  /** The same routing the call uses, so the estimate names the endpoint billed. */
  referenceRoute(modelId, referenceCount) {
    const route = resolveReferenceRoute(imageGenModel(falImageGen, modelId).id, referenceCount)
    return route ? { id: route.id, label: route.label, pricePerImage: route.pricePerImage } : null
  },

  /**
   * fal has no free "who am I" endpoint, so this leans on the run endpoint's
   * auth check: a GET is the wrong method, and fal validates the key BEFORE
   * the method — an invalid key answers 401, a valid one answers 405. Only
   * auth failures are treated as failures; everything else proves the key
   * was accepted without buying an image.
   */
  async verifyKey(apiKey, options = {}) {
    const fetchImpl = options.fetchImpl ?? fetch
    let response: Response
    try {
      response = await fetchImpl(endpoint(MODELS[0].id), {
        method: 'GET',
        headers: { Authorization: `Key ${apiKey}` },
        ...(options.signal ? { signal: options.signal } : {}),
      })
    } catch (cause) {
      throw mapNetworkError('fal', cause)
    }
    if (response.status === 401 || response.status === 403) {
      await throwForResponse('fal', response)
    }
  },
}
